name: vosk_flutter
description: Flutter plugin for offline speech recognition using the Vosk speech recognition toolkit.
version: 0.3.48
homepage: https://alphacephei.com/
repository: https://github.com/alphacep/vosk-flutter

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  archive: ^3.1.8
  args: ^2.4.0
  build_cli_annotations: ^2.1.0
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  http: ^0.13.5
  package_config: ^2.1.0
  path: ^1.8.2
  path_provider: ^2.0.8
  permission_handler: ^10.2.0
  pubspec_parse: ^1.2.2

dev_dependencies:
  build_cli: ^2.2.1
  build_runner: ^2.3.3
  ffigen: ^7.2.9
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

ffigen:
  name: VoskLibrary
  output: 'lib/src/generated_vosk_bindings.dart'
  headers:
    entry-points:
      - 'vosk-api/src/vosk_api.h'

flutter:
  plugin:
    platforms:
      android:
        package: org.vosk.vosk_flutter
        pluginClass: VoskFlutterPlugin
      linux:
        pluginClass: VoskFlutterPlugin
        ffiPlugin: true
      windows:
        pluginClass: VoskFlutterPlugin
        ffiPlugin: true
